Repository PDAL/java, pull requests merged in 2024-01, with the labels that each got.

#73 PDAL 2.6.x
  .github/workflows/ci.yml
  .scalafmt.conf
  build.sbt
  core/src/main/scala/io/pdal/Pipeline.scala
  core/src/test/resources/quick-info-with-metadata-mac.json
  core/src/test/resources/quick-info-with-metadata.json
  core/src/test/resources/quick-info.json
  core/src/test/resources/schema.json
  core/src/test/scala/io/pdal/PipelineSpec.scala
  native/src/CMakeLists.txt
  project/Dependencies.scala
  project/build.properties
  scripts/crosscompile-linux.sh
  scripts/docker/2.6.0/ubuntu/Dockerfile
Labels: feature

#74 Cache Conda in CI
  .github/workflows/ci.yml
  sbt
Labels: build

#75 Update README.md adding java example
  README.md
Labels: docs

#77 Expand Code examples in README.md
  README.md
  examples/pdal-jni/sbt
  examples/pdal-jni/src/main/java/com/azavea/MainJava.java
Labels: docs

#78 Plugins update & minor improvements
  .gitignore
  .scalafmt.conf
  native/src/JavaPipeline.cpp
  project/plugins.sbt
  scripts/README.md
  scripts/crosscompile-linux.sh
  scripts/docker/2.6.0/ubuntu/Dockerfile
  scripts/publish-local-native.sh
  scripts/publish-local.sh
  scripts/publish-native.sh
  scripts/publish.sh
Labels: bug, dependencies

#80 Improve java_error messages
  native/src/JavaPipeline.cpp
  native/src/include/JavaSetIterator.hpp
  native/src/include/JavaTriangularMeshIterator.hpp
Labels: enhancement

#82 Fix Failing Logging capture
  README.md
  core/src/main/scala/io/pdal/LogLevel.scala
  core/src/main/scala/io/pdal/Pipeline.scala
  core/src/test/scala/io/pdal/PipelineSpec.scala
  examples/pdal-jni/data/issue-79.las
  examples/pdal-jni/src/main/scala/com/azavea/MainLogging.scala
  native/src/JavaPipeline.cpp
  native/src/include/JavaPipeline.hpp
  native/src/include/io_pdal_Pipeline.h
  native/src/io_pdal_Pipeline.cpp
Labels: bug

#83 core-scala toPipeline logLevel support
  core-scala/src/main/scala/io/pdal/pipeline/PipelineConstructor.scala
  examples/pdal-jni/README.md
  examples/pdal-jni/src/main/scala/com/azavea/MainLogging.scala
Labels: enhancement

#81 Refactor the readme file
  README.md
Labels: docs
