Repository PDAL/java, pull requests merged in 2024-03, with the labels that each got.

#87 Update actions
  .github/workflows/ci.yml
  .github/workflows/release-drafter.yml
Labels: build

#95 Added extra rpath entries to common macOS library install locations.
  .github/workflows/ci.yml
  README.md
  native/src/CMakeLists.txt
Labels: enhancement

#96 cmake list delimiter should be `;`
  native/src/CMakeLists.txt
Labels: bug

#94 Call initialize in the Pipeline public constructor
  README.md
  core/src/main/scala/io/pdal/Pipeline.scala
Labels: enhancement

#97 PDAL 2.7.x
  .github/workflows/ci.yml
  README.md
  examples/pdal-jni/build.sbt
  examples/pdal-jni/src/main/java/com/azavea/MainJava.java
Labels: enhancement

#99 Update PDAL JNI lib version
  core/src/main/scala/io/pdal/Pipeline.scala
  examples/pdal-jni/build.sbt
  native/src/CMakeLists.txt
Labels: enhancement

#100 Upd PDAL up to 2.7.1
  .github/workflows/ci.yml
Labels: dependencies
